/*
 * Created on 2025-02-15 ( Time 03:02:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package dev.backend.epharmaApp.dao.entity;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ChatRoomParticipantsEntity" ( stored in table "chat_room_participants" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ChatRoomParticipantsKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="room_id", nullable=false)
    private Integer    roomId       ;
    
    @Column(name="user_id", nullable=false)
    private Integer    userId       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ChatRoomParticipantsKey() {
        super();
    }

    public ChatRoomParticipantsKey( Integer roomId, Integer userId ) {
        super();
        this.roomId = roomId ;
        this.userId = userId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setRoomId( Integer value ) {
        this.roomId = value;
    }
    public Integer getRoomId() {
        return this.roomId;
    }

    public void setUserId( Integer value ) {
        this.userId = value;
    }
    public Integer getUserId() {
        return this.userId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ChatRoomParticipantsKey other = (ChatRoomParticipantsKey) obj; 
		//--- Attribute roomId
		if ( roomId == null ) { 
			if ( other.roomId != null ) 
				return false ; 
		} else if ( ! roomId.equals(other.roomId) ) 
			return false ; 
		//--- Attribute userId
		if ( userId == null ) { 
			if ( other.userId != null ) 
				return false ; 
		} else if ( ! userId.equals(other.userId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute roomId
		result = prime * result + ((roomId == null) ? 0 : roomId.hashCode() ) ; 
		//--- Attribute userId
		result = prime * result + ((userId == null) ? 0 : userId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(roomId); 
		sb.append("|"); 
		sb.append(userId); 
        return sb.toString();
    }
}
