/*
 * Created on 2025-02-15 ( Time 03:02:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package dev.backend.epharmaApp.dao.entity;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ClientRolesEntity" ( stored in table "client_roles" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ClientRolesKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="client_id", nullable=false)
    private Integer    clientId     ;
    
    @Column(name="role_id", nullable=false)
    private Integer    roleId       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ClientRolesKey() {
        super();
    }

    public ClientRolesKey( Integer clientId, Integer roleId ) {
        super();
        this.clientId = clientId ;
        this.roleId = roleId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setClientId( Integer value ) {
        this.clientId = value;
    }
    public Integer getClientId() {
        return this.clientId;
    }

    public void setRoleId( Integer value ) {
        this.roleId = value;
    }
    public Integer getRoleId() {
        return this.roleId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ClientRolesKey other = (ClientRolesKey) obj; 
		//--- Attribute clientId
		if ( clientId == null ) { 
			if ( other.clientId != null ) 
				return false ; 
		} else if ( ! clientId.equals(other.clientId) ) 
			return false ; 
		//--- Attribute roleId
		if ( roleId == null ) { 
			if ( other.roleId != null ) 
				return false ; 
		} else if ( ! roleId.equals(other.roleId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute clientId
		result = prime * result + ((clientId == null) ? 0 : clientId.hashCode() ) ; 
		//--- Attribute roleId
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(clientId); 
		sb.append("|"); 
		sb.append(roleId); 
        return sb.toString();
    }
}
