/*
 * Created on 2025-02-15 ( Time 03:02:41 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package dev.backend.epharmaApp.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "deliveries"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="deliveries" )
public class Deliveries implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="delivery_id", nullable=false)
    private Integer    deliveryId   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="delivery_status", nullable=false, length=50)
    private String     deliveryStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expected_delivery_date")
    private Date       expectedDeliveryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actual_delivery_date")
    private Date       actualDeliveryDate ;

    @Column(name="tracking_number", length=100)
    private String     trackingNumber ;

    @Column(name="delivery_method", length=8)
    private String     deliveryMethod ;

    @Column(name="record_status", length=50)
    private String     recordStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

	// "orderId" (column "order_id") is not defined by itself because used as FK in a link 
	// "pharmacyId" (column "pharmacy_id") is not defined by itself because used as FK in a link 
	// "assignedTo" (column "assigned_to") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="order_id")
    private Orders orders      ;
    @ManyToOne
    @JoinColumn(name="pharmacy_id", referencedColumnName="pharmacy_id")
    private Pharmacies pharmacies  ;
    @ManyToOne
    @JoinColumn(name="assigned_to", referencedColumnName="user_id")
    private Users users       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Deliveries() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
