/*
 * Created on 2025-02-15 ( Time 03:02:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package dev.backend.epharmaApp.dao.entity;

import lombok.Data;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * Persistent class for entity stored in table "products"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="products" )
public class Products implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="product_id", nullable=false)
    private Integer    productId    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="product_name", nullable=false, length=150)
    private String     productName  ;

    @Column(name="generic_name", length=150)
    private String     genericName  ;

    @Column(name="brand_name", length=150)
    private String     brandName    ;

    @Column(name="description", length=65535)
    private String     description  ;

    @Column(name="dosage", length=100)
    private String     dosage       ;

    @Column(name="price", nullable=false)
    private Double price        ;

    @Column(name="barcode", length=100)
    private String     barcode      ;

    @Temporal(TemporalType.DATE)
    @Column(name="expiration_date")
    private Date       expirationDate ;

    @Column(name="record_status", length=50)
    private String     recordStatus ;

    @Column(name="photo", length=65535)
    private String     photo        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

	// "categoryId" (column "category_id") is not defined by itself because used as FK in a link 
	// "manufacturerId" (column "manufacturer_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="category_id", referencedColumnName="category_id")
    private ProductCategories productCategories;
    @ManyToOne
    @JoinColumn(name="manufacturer_id", referencedColumnName="manufacturer_id")
    private Manufacturers manufacturers;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Products() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
