/*
 * Created on 2025-02-15 ( Time 03:02:46 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package dev.backend.epharmaApp.dao.entity;
import lombok.Data;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "RolePermissionsEntity" ( stored in table "role_permissions" )
 *
 * @author Telosys Tools Generator
 *
 */
@Data
 @Embeddable
public class RolePermissionsKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="role_id", nullable=false)
    private Integer    roleId       ;
    
    @Column(name="permission_id", nullable=false)
    private Integer    permissionId ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public RolePermissionsKey() {
        super();
    }

    public RolePermissionsKey( Integer roleId, Integer permissionId ) {
        super();
        this.roleId = roleId ;
        this.permissionId = permissionId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setRoleId( Integer value ) {
        this.roleId = value;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setPermissionId( Integer value ) {
        this.permissionId = value;
    }
    public Integer getPermissionId() {
        return this.permissionId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		RolePermissionsKey other = (RolePermissionsKey) obj; 
		//--- Attribute roleId
		if ( roleId == null ) { 
			if ( other.roleId != null ) 
				return false ; 
		} else if ( ! roleId.equals(other.roleId) ) 
			return false ; 
		//--- Attribute permissionId
		if ( permissionId == null ) { 
			if ( other.permissionId != null ) 
				return false ; 
		} else if ( ! permissionId.equals(other.permissionId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute roleId
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode() ) ; 
		//--- Attribute permissionId
		result = prime * result + ((permissionId == null) ? 0 : permissionId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(roleId); 
		sb.append("|"); 
		sb.append(permissionId); 
        return sb.toString();
    }
}
