/*
 * Created on 2025-02-15 ( Time 03:02:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package dev.backend.epharmaApp.dao.entity;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "StockEntity" ( stored in table "stock" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class StockKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="pharmacy_id", nullable=false)
    private Integer    pharmacyId   ;
    
    @Column(name="product_id", nullable=false)
    private Integer    productId    ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public StockKey() {
        super();
    }

    public StockKey( Integer pharmacyId, Integer productId ) {
        super();
        this.pharmacyId = pharmacyId ;
        this.productId = productId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setPharmacyId( Integer value ) {
        this.pharmacyId = value;
    }
    public Integer getPharmacyId() {
        return this.pharmacyId;
    }

    public void setProductId( Integer value ) {
        this.productId = value;
    }
    public Integer getProductId() {
        return this.productId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		StockKey other = (StockKey) obj; 
		//--- Attribute pharmacyId
		if ( pharmacyId == null ) { 
			if ( other.pharmacyId != null ) 
				return false ; 
		} else if ( ! pharmacyId.equals(other.pharmacyId) ) 
			return false ; 
		//--- Attribute productId
		if ( productId == null ) { 
			if ( other.productId != null ) 
				return false ; 
		} else if ( ! productId.equals(other.productId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute pharmacyId
		result = prime * result + ((pharmacyId == null) ? 0 : pharmacyId.hashCode() ) ; 
		//--- Attribute productId
		result = prime * result + ((productId == null) ? 0 : productId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(pharmacyId); 
		sb.append("|"); 
		sb.append(productId); 
        return sb.toString();
    }
}
