/*
 * Created on 2025-02-15 ( Time 03:02:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package dev.backend.epharmaApp.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "users"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="users" )
public class Users implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="user_id", nullable=false)
    private Integer    userId       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="login", length=100)
    private String     login        ;

    @Column(name="email", nullable=false, length=150)
    private String     email        ;

    @Column(name="first_name", nullable=false, length=100)
    private String     firstName    ;

    @Column(name="last_name", nullable=false, length=100)
    private String     lastName     ;

    @Column(name="password_hash", nullable=false, length=255)
    private String     passwordHash ;

    @Column(name="phone", length=50)
    private String     phone        ;

    @Column(name="address", length=255)
    private String     address      ;

    @Column(name="city", length=100)
    private String     city         ;

    @Column(name="country", length=100)
    private String     country      ;

    @Column(name="record_status", length=50)
    private String     recordStatus ;

    @Column(name="is_active")
    private Boolean    isActive     ;

    @Column(name="is_locked")
    private Boolean    isLocked     ;

    @Column(name="is_client")
    private Boolean    isClient     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

	// "pharmacyId" (column "pharmacy_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="pharmacy_id", referencedColumnName="pharmacy_id")
    private Pharmacies pharmacies  ;

    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="role_id")
    private Roles roles  ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Users() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
