/*
 * Created on 2025-02-15 ( Time 03:02:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package dev.backend.epharmaApp.dao.entity;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "UserRolesEntity" ( stored in table "user_roles" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class UserRolesKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="user_id", nullable=false)
    private Integer    userId       ;
    
    @Column(name="role_id", nullable=false)
    private Integer    roleId       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public UserRolesKey() {
        super();
    }

    public UserRolesKey( Integer userId, Integer roleId ) {
        super();
        this.userId = userId ;
        this.roleId = roleId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer value ) {
        this.userId = value;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setRoleId( Integer value ) {
        this.roleId = value;
    }
    public Integer getRoleId() {
        return this.roleId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		UserRolesKey other = (UserRolesKey) obj; 
		//--- Attribute userId
		if ( userId == null ) { 
			if ( other.userId != null ) 
				return false ; 
		} else if ( ! userId.equals(other.userId) ) 
			return false ; 
		//--- Attribute roleId
		if ( roleId == null ) { 
			if ( other.roleId != null ) 
				return false ; 
		} else if ( ! roleId.equals(other.roleId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute userId
		result = prime * result + ((userId == null) ? 0 : userId.hashCode() ) ; 
		//--- Attribute roleId
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(userId); 
		sb.append("|"); 
		sb.append(roleId); 
        return sb.toString();
    }
}
