/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package dev.backend.epharmaApp.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// CHAT_MESSAGE_ATTACHMENTS
	VIEW_CHAT_MESSAGE_ATTACHMENTS("VIEW_CHAT_MESSAGE_ATTACHMENTS"),	
	CREATE_CHAT_MESSAGE_ATTACHMENTS("CREATE_CHAT_MESSAGE_ATTACHMENTS"),
	UPDATE_CHAT_MESSAGE_ATTACHMENTS("UPDATE_CHAT_MESSAGE_ATTACHMENTS"),
	DELETE_CHAT_MESSAGE_ATTACHMENTS("DELETE_CHAT_MESSAGE_ATTACHMENTS"),
	// CHAT_MESSAGES
	VIEW_CHAT_MESSAGES("VIEW_CHAT_MESSAGES"),	
	CREATE_CHAT_MESSAGES("CREATE_CHAT_MESSAGES"),
	UPDATE_CHAT_MESSAGES("UPDATE_CHAT_MESSAGES"),
	DELETE_CHAT_MESSAGES("DELETE_CHAT_MESSAGES"),
	// CHAT_ROOM_PARTICIPANTS
	VIEW_CHAT_ROOM_PARTICIPANTS("VIEW_CHAT_ROOM_PARTICIPANTS"),	
	CREATE_CHAT_ROOM_PARTICIPANTS("CREATE_CHAT_ROOM_PARTICIPANTS"),
	UPDATE_CHAT_ROOM_PARTICIPANTS("UPDATE_CHAT_ROOM_PARTICIPANTS"),
	DELETE_CHAT_ROOM_PARTICIPANTS("DELETE_CHAT_ROOM_PARTICIPANTS"),
	// CHAT_ROOMS
	VIEW_CHAT_ROOMS("VIEW_CHAT_ROOMS"),	
	CREATE_CHAT_ROOMS("CREATE_CHAT_ROOMS"),
	UPDATE_CHAT_ROOMS("UPDATE_CHAT_ROOMS"),
	DELETE_CHAT_ROOMS("DELETE_CHAT_ROOMS"),
	// CLIENT_ROLES
	VIEW_CLIENT_ROLES("VIEW_CLIENT_ROLES"),	
	CREATE_CLIENT_ROLES("CREATE_CLIENT_ROLES"),
	UPDATE_CLIENT_ROLES("UPDATE_CLIENT_ROLES"),
	DELETE_CLIENT_ROLES("DELETE_CLIENT_ROLES"),
	// CLIENTS
	VIEW_CLIENTS("VIEW_CLIENTS"),	
	CREATE_CLIENTS("CREATE_CLIENTS"),
	UPDATE_CLIENTS("UPDATE_CLIENTS"),
	DELETE_CLIENTS("DELETE_CLIENTS"),
	// DELIVERIES
	VIEW_DELIVERIES("VIEW_DELIVERIES"),	
	CREATE_DELIVERIES("CREATE_DELIVERIES"),
	UPDATE_DELIVERIES("UPDATE_DELIVERIES"),
	DELETE_DELIVERIES("DELETE_DELIVERIES"),
	// DELIVERY_PERSON_PROFILES
	VIEW_DELIVERY_PERSON_PROFILES("VIEW_DELIVERY_PERSON_PROFILES"),	
	CREATE_DELIVERY_PERSON_PROFILES("CREATE_DELIVERY_PERSON_PROFILES"),
	UPDATE_DELIVERY_PERSON_PROFILES("UPDATE_DELIVERY_PERSON_PROFILES"),
	DELETE_DELIVERY_PERSON_PROFILES("DELETE_DELIVERY_PERSON_PROFILES"),
	// MANUFACTURERS
	VIEW_MANUFACTURERS("VIEW_MANUFACTURERS"),	
	CREATE_MANUFACTURERS("CREATE_MANUFACTURERS"),
	UPDATE_MANUFACTURERS("UPDATE_MANUFACTURERS"),
	DELETE_MANUFACTURERS("DELETE_MANUFACTURERS"),
	// NOTICES
	VIEW_NOTICES("VIEW_NOTICES"),	
	CREATE_NOTICES("CREATE_NOTICES"),
	UPDATE_NOTICES("UPDATE_NOTICES"),
	DELETE_NOTICES("DELETE_NOTICES"),
	// ORDER_ITEMS
	VIEW_ORDER_ITEMS("VIEW_ORDER_ITEMS"),	
	CREATE_ORDER_ITEMS("CREATE_ORDER_ITEMS"),
	UPDATE_ORDER_ITEMS("UPDATE_ORDER_ITEMS"),
	DELETE_ORDER_ITEMS("DELETE_ORDER_ITEMS"),
	// ORDERS
	VIEW_ORDERS("VIEW_ORDERS"),	
	CREATE_ORDERS("CREATE_ORDERS"),
	UPDATE_ORDERS("UPDATE_ORDERS"),
	DELETE_ORDERS("DELETE_ORDERS"),
	// PERMISSIONS
	VIEW_PERMISSIONS("VIEW_PERMISSIONS"),	
	CREATE_PERMISSIONS("CREATE_PERMISSIONS"),
	UPDATE_PERMISSIONS("UPDATE_PERMISSIONS"),
	DELETE_PERMISSIONS("DELETE_PERMISSIONS"),
	// PHARMACIES
	VIEW_PHARMACIES("VIEW_PHARMACIES"),	
	CREATE_PHARMACIES("CREATE_PHARMACIES"),
	UPDATE_PHARMACIES("UPDATE_PHARMACIES"),
	DELETE_PHARMACIES("DELETE_PHARMACIES"),
	// PHARMACY_RATINGS
	VIEW_PHARMACY_RATINGS("VIEW_PHARMACY_RATINGS"),	
	CREATE_PHARMACY_RATINGS("CREATE_PHARMACY_RATINGS"),
	UPDATE_PHARMACY_RATINGS("UPDATE_PHARMACY_RATINGS"),
	DELETE_PHARMACY_RATINGS("DELETE_PHARMACY_RATINGS"),
	// PRESCRIPTION_ITEMS
	VIEW_PRESCRIPTION_ITEMS("VIEW_PRESCRIPTION_ITEMS"),	
	CREATE_PRESCRIPTION_ITEMS("CREATE_PRESCRIPTION_ITEMS"),
	UPDATE_PRESCRIPTION_ITEMS("UPDATE_PRESCRIPTION_ITEMS"),
	DELETE_PRESCRIPTION_ITEMS("DELETE_PRESCRIPTION_ITEMS"),
	// PRESCRIPTIONS
	VIEW_PRESCRIPTIONS("VIEW_PRESCRIPTIONS"),	
	CREATE_PRESCRIPTIONS("CREATE_PRESCRIPTIONS"),
	UPDATE_PRESCRIPTIONS("UPDATE_PRESCRIPTIONS"),
	DELETE_PRESCRIPTIONS("DELETE_PRESCRIPTIONS"),
	// PRODUCT_CATEGORIES
	VIEW_PRODUCT_CATEGORIES("VIEW_PRODUCT_CATEGORIES"),	
	CREATE_PRODUCT_CATEGORIES("CREATE_PRODUCT_CATEGORIES"),
	UPDATE_PRODUCT_CATEGORIES("UPDATE_PRODUCT_CATEGORIES"),
	DELETE_PRODUCT_CATEGORIES("DELETE_PRODUCT_CATEGORIES"),
	// PRODUCT_MOVEMENTS
	VIEW_PRODUCT_MOVEMENTS("VIEW_PRODUCT_MOVEMENTS"),	
	CREATE_PRODUCT_MOVEMENTS("CREATE_PRODUCT_MOVEMENTS"),
	UPDATE_PRODUCT_MOVEMENTS("UPDATE_PRODUCT_MOVEMENTS"),
	DELETE_PRODUCT_MOVEMENTS("DELETE_PRODUCT_MOVEMENTS"),
	// PRODUCTS
	VIEW_PRODUCTS("VIEW_PRODUCTS"),	
	CREATE_PRODUCTS("CREATE_PRODUCTS"),
	UPDATE_PRODUCTS("UPDATE_PRODUCTS"),
	DELETE_PRODUCTS("DELETE_PRODUCTS"),
	// PURCHASE_ORDER_ITEMS
	VIEW_PURCHASE_ORDER_ITEMS("VIEW_PURCHASE_ORDER_ITEMS"),	
	CREATE_PURCHASE_ORDER_ITEMS("CREATE_PURCHASE_ORDER_ITEMS"),
	UPDATE_PURCHASE_ORDER_ITEMS("UPDATE_PURCHASE_ORDER_ITEMS"),
	DELETE_PURCHASE_ORDER_ITEMS("DELETE_PURCHASE_ORDER_ITEMS"),
	// PURCHASE_ORDERS
	VIEW_PURCHASE_ORDERS("VIEW_PURCHASE_ORDERS"),	
	CREATE_PURCHASE_ORDERS("CREATE_PURCHASE_ORDERS"),
	UPDATE_PURCHASE_ORDERS("UPDATE_PURCHASE_ORDERS"),
	DELETE_PURCHASE_ORDERS("DELETE_PURCHASE_ORDERS"),
	// ROLE_PERMISSIONS
	VIEW_ROLE_PERMISSIONS("VIEW_ROLE_PERMISSIONS"),	
	CREATE_ROLE_PERMISSIONS("CREATE_ROLE_PERMISSIONS"),
	UPDATE_ROLE_PERMISSIONS("UPDATE_ROLE_PERMISSIONS"),
	DELETE_ROLE_PERMISSIONS("DELETE_ROLE_PERMISSIONS"),
	// ROLES
	VIEW_ROLES("VIEW_ROLES"),	
	CREATE_ROLES("CREATE_ROLES"),
	UPDATE_ROLES("UPDATE_ROLES"),
	DELETE_ROLES("DELETE_ROLES"),
	// STOCK
	VIEW_STOCK("VIEW_STOCK"),	
	CREATE_STOCK("CREATE_STOCK"),
	UPDATE_STOCK("UPDATE_STOCK"),
	DELETE_STOCK("DELETE_STOCK"),
	// STOCK_ALERTS
	VIEW_STOCK_ALERTS("VIEW_STOCK_ALERTS"),	
	CREATE_STOCK_ALERTS("CREATE_STOCK_ALERTS"),
	UPDATE_STOCK_ALERTS("UPDATE_STOCK_ALERTS"),
	DELETE_STOCK_ALERTS("DELETE_STOCK_ALERTS"),
	// STOCK_AUDIT
	VIEW_STOCK_AUDIT("VIEW_STOCK_AUDIT"),	
	CREATE_STOCK_AUDIT("CREATE_STOCK_AUDIT"),
	UPDATE_STOCK_AUDIT("UPDATE_STOCK_AUDIT"),
	DELETE_STOCK_AUDIT("DELETE_STOCK_AUDIT"),
	// USER_RATINGS
	VIEW_USER_RATINGS("VIEW_USER_RATINGS"),	
	CREATE_USER_RATINGS("CREATE_USER_RATINGS"),
	UPDATE_USER_RATINGS("UPDATE_USER_RATINGS"),
	DELETE_USER_RATINGS("DELETE_USER_RATINGS"),
	// USER_ROLES
	VIEW_USER_ROLES("VIEW_USER_ROLES"),	
	CREATE_USER_ROLES("CREATE_USER_ROLES"),
	UPDATE_USER_ROLES("UPDATE_USER_ROLES"),
	DELETE_USER_ROLES("DELETE_USER_ROLES"),
	// USERS
	VIEW_USERS("VIEW_USERS"),	
	CREATE_USERS("CREATE_USERS"),
	UPDATE_USERS("UPDATE_USERS"),
	DELETE_USERS("DELETE_USERS"),
	VIEW_API_LOGS("VIEW_API_LOGS"),
	CREATE_API_LOGS("CREATE_API_LOGS"),
	UPDATE_API_LOGS("UPDATE_API_LOGS"),
	DELETE_API_LOGS("DELETE_API_LOGS"),
	// LOGS
	// LOGS
	VIEW_LOGS("VIEW_LOGS"),
	CREATE_LOGS("CREATE_LOGS"),
	UPDATE_LOGS("UPDATE_LOGS"),
	DELETE_LOGS("DELETE_LOGS"),
	// PARAM_NOTIFICATION
	VIEW_PARAM_NOTIFICATION("VIEW_PARAM_NOTIFICATION"),
	CREATE_PARAM_NOTIFICATION("CREATE_PARAM_NOTIFICATION"),
	UPDATE_PARAM_NOTIFICATION("UPDATE_PARAM_NOTIFICATION"),
	DELETE_PARAM_NOTIFICATION("DELETE_PARAM_NOTIFICATION"),
	// PARAMETRE_GENERAUX
	VIEW_PARAMETRE_GENERAUX("VIEW_PARAMETRE_GENERAUX"),
	CREATE_PARAMETRE_GENERAUX("CREATE_PARAMETRE_GENERAUX"),
	UPDATE_PARAMETRE_GENERAUX("UPDATE_PARAMETRE_GENERAUX"),
	DELETE_PARAMETRE_GENERAUX("DELETE_PARAMETRE_GENERAUX");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
